# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170915_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
