# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
