# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170915_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_photo',
        ),
    ]
