# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_plants_plant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='currentplant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
