# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171007_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='currentplant',
        ),
    ]
