# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_members_plants_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='currentplant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
