# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_users_currentplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vehicleCount',
            field=models.IntegerField(default=0),
        ),
    ]
