# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_users_reservoircount'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='currentreservoir',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
