# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170830_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='plant_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
