# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20171005_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
