# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20171005_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantsensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilmoisture', models.FloatField()),
                ('userid', models.IntegerField()),
                ('plant_name', models.CharField(max_length=150, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('actualHieght', models.FloatField()),
                ('userid', models.IntegerField()),
                ('plant_name', models.CharField(max_length=150, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weathersensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryid', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('seapressure', models.FloatField()),
                ('userid', models.IntegerField()),
                ('plant_name', models.CharField(max_length=150, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='temperature',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
        migrations.AddField(
            model_name='plantsensors',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
    ]
