# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20171005_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantsensors',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plantsensors',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='plantsensors',
            name='time',
        ),
        migrations.RemoveField(
            model_name='plantsensors',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='userid',
        ),
    ]
