# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_remove_weathersensors_entryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsensors',
            name='entryid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='entryid',
            field=models.IntegerField(),
        ),
    ]
