# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_auto_20171005_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsensors',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
    ]
