# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_auto_20171006_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathersensors',
            name='plant_name',
        ),
        migrations.AddField(
            model_name='weathersensors',
            name='plant_id',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
