# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0014_auto_20171007_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantsensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilmoisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('actualHieght', models.FloatField(default=35)),
                ('ph', models.FloatField()),
                ('turbidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='weathersensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rain', models.FloatField()),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservoir',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
        migrations.AddField(
            model_name='plantsensors',
            name='entryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors'),
        ),
    ]
