# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_users_reservoircount'),
        ('sensors', '0015_auto_20171008_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
            preserve_default=False,
        ),
    ]
