# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_reservoir_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='reservoirname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
