# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_reservoir_reservoirname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoir',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='turbidity',
            field=models.FloatField(default=0),
        ),
    ]
