# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_auto_20171008_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservoirdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.weathersensors')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='actualHieght',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='entryid',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='turbidity',
        ),
    ]
