# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_auto_20171008_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoirdata',
            name='actualHieght',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='reservoirdata',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservoirdata',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservoirdata',
            name='turbidity',
            field=models.FloatField(default=0),
        ),
    ]
