# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0021_reservoirdata_reservoirid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersensors',
            name='rain',
            field=models.IntegerField(),
        ),
    ]
