# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_auto_20171008_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='volume',
            field=models.FloatField(default=10),
        ),
    ]
