# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0023_reservoir_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersensors',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
